apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
    spec:
      containers:
      - image: alatui/hello-world:61c79c8aaafae80fbf7173a42e56eae027b6348e
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 80
        env:
        - name: HELLO
          value: "HI"
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-world
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: hello-world
              servicePort: 80
