name: master

on:
  push:
    branches:
      - 'master'

jobs:
  new_release:
    name: Deploy new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      IMAGE: alatui/hello-world:${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        working-directory: ./apps/hello-world
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Update yaml definitions
        working-directory: ./apps/hello-world
        run: |
          sed -i.bak "s/image: .*/image: alatui\/hello-world:${{ github.sha }}/" app.yaml
      - name: New release
        run: |
          git config --global user.name 'GitHub CI BOT'
          git config --global user.email 'github-ci-bot@personio.de'
          git commit -am "feat: hello-world new app release"
          git push
