name: pr

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build_pr:
    name: Build PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE: alatui/hello-world:${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: ./apps/hello-world
        run: |
          docker build -t $IMAGE .
